<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Account Export</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th colspan="5" style="text-transform: uppercase; font-size: 20px; text-align: center">
                    RK MOBILES
                </th>
            </tr>
            <tr>
                <th colspan="5" style="text-transform: uppercase; font-size: 14px; text-align: left">
                    Account Expense Summery Report
                </th>
            </tr>
            <tr></tr>
            <tr>
                <th colspan="5">
                    @if ((isset($request->year) && !empty($request->year)) && (isset($request->month) && !empty($request->month)))
                        @php
                            $year_month_r = $request->year.'-'.$request->month;
                        @endphp
                        Report For : {{date('Y - F', strtotime($year_month_r))}}
                    @endif
                </th>
            </tr>

            <tr></tr>
            <tr>
                <th colspan="5" style="text-transform: uppercase; text-align: right">
                    Generated By : {{Auth::user()->name}}
                </th>
            </tr>
            <tr>
                <th colspan="5" style="text-transform: uppercase; text-align: right">
                    Generated At : {{date('M, d Y h:i A')}}
                </th>
            </tr>

            <tr></tr>

            <tr>
                <th style="font-weight: 600; text-align: center">#</th>
                <th style="font-weight: 600; text-align: center">Category</th>
                <th style="font-weight: 600; text-align: center">Year - Month</th>
                <th style="font-weight: 600; text-align: center">Date</th>
                <th style="font-weight: 600; text-align: center">Amount</th>
            </tr>
        </thead>
        <tbody>
            @if (count($expenses))
                @php
                    $i = 0;
                    $total = 0;
                @endphp
                @foreach ($expenses as $item)
                    @php
                        $i++;
                        $year_month = $item->year.'-'.$item->month;
                        $total = $total + $item->amount;
                    @endphp

                    <tr>
                        <td>{{$i}}</td>
                        <td>{{ucwords($item->getCategory->category)}}</td>
                        <td>{{date('Y - F', strtotime($year_month))}}</td>
                        <td>{{$item->paid_date}}</td>
                        <td style="text-align: right">{{number_format($item->amount,2)}}</td>
                    </tr>

                @endforeach
                    <tr>
                        <td colspan="4" style="text-align: right; background-color: gray; color:#fff; font-size: 13px">Total</td>
                        <td  style="text-align: right; background-color: gray; color:#fff; font-size: 13px">{{number_format($total,2)}}</td>
                    </tr>

            @else
                <tr>
                    <th colspan="5" style="text-transform: uppercase; font-size: 14px; text-align: center">
                        No Data Found!
                    </th>
                </tr>
            @endif

        </tbody>
    </table>
</body>
</html>
