<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventory Export</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th colspan="7" style="text-transform: uppercase; font-size: 20px; text-align: center">
                    RK MOBILES
                </th>
            </tr>
            <tr>
                <th colspan="7" style="text-transform: uppercase; font-size: 16px; text-align: left">
                    Inventory Summery Report
                </th>
            </tr>
            <tr></tr>
            <tr>
                <th colspan="7">
                    @if ($category != '')
                        Category : {{$category}}
                    @endif
                </th>
            </tr>

            <tr></tr>
            <tr>
                <th colspan="7" style="text-transform: uppercase; text-align: right">
                    Generated By : {{Auth::user()->name}}
                </th>
            </tr>
            <tr>
                <th colspan="7" style="text-transform: uppercase; text-align: right">
                    Generated At : {{date('M, d Y h:i A')}}
                </th>
            </tr>

            <tr></tr>

            <tr>
                <th style="font-weight: 600; text-align: center">#</th>
                <th style="font-weight: 600; text-align: center">Code</th>
                <th style="font-weight: 600; text-align: center">Product Name</th>
                <th style="font-weight: 600; text-align: center">Category</th>
                <th style="font-weight: 600; text-align: center">Selling Price</th>
                <th style="font-weight: 600; text-align: center">Available Qty</th>
                <th style="font-weight: 600; text-align: center">Status</th>
            </tr>
        </thead>
        <tbody>
            @if (count($inventory))
                @php
                    $i = 0;
                @endphp
                @foreach ($inventory as $item)
                    @php
                        $i++;
                    @endphp

                    <tr>
                        <td>{{$i}}</td>
                        <td>{{$item->code}}</td>
                        <td>{{$item->name}}</td>
                        <td>{{$item->category->name}}</td>
                        <td style="text-align: right">{{number_format($item->price,2)}}</td>
                        <td style="text-align: center">{{$item->qty}}</td>
                        <td style="text-align: center">{{$item->status == '0' ? 'Inactive' : 'Active'}}</td>
                    </tr>

                @endforeach

            @else
                <tr>
                    <th colspan="7" style="text-transform: uppercase; font-size: 14px; text-align: center">
                        No Data Found!
                    </th>
                </tr>
            @endif

        </tbody>
    </table>
</body>
</html>
